var express = require('express')
var router = express.Router()
const analysis = require('../controllers/analysis')

router.get('/scores/:foodId', analysis.userDefinedScore)
router.get('/foodLikert/data', analysis.getFoodOpinion)
router.get('/user/:userId', analysis.showSortingsPerUser)
router.get('/compareSort', analysis.showSortings)
router.get('/compareSort/distance', analysis.showDistance)
router.get('/dietAvg', analysis.getDietarySummary)
router.get('/diet/data', analysis.getDietaryData)
router.get('/postSurvey1', analysis.getPost1Summary)
router.get('/sortProcess/:userId', analysis.sortingProcess)
router.get('/postSurvey1/data', analysis.getPost1Detail)
router.get('/sortings/data/:trial', analysis.getAllSortings)
router.get('/postSurvey2', analysis.getPost2Summary)
router.get('/postSurvey2/data', analysis.getPost2Detail)
router.get('/userChoice/data/:trial', analysis.getUserChoiceData)
router.get('/userChoice/:trial', analysis.userChoices)
router.get('/time/data', analysis.getTimeConsumption)
router.get('/choosingProcess/data', analysis.getChoosingProcess)
router.get('/foodScore/data', analysis.getAllFoodScores)

module.exports = router
