ALTER TABLE hpbdata
ADD COLUMN image bytea;

UPDATE hpbdata SET image = '/images/Thosai.jpg' WHERE id = '2734';
UPDATE hpbdata SET image = '/images/Idli.jpg' WHERE id = '1340';
UPDATE hpbdata SET image = '/images/Mee rebus.jpg' WHERE id = '1587';
UPDATE hpbdata SET image = '/images/Butterfly fritter.jpg' WHERE id = '448';
UPDATE hpbdata SET image = '/images/Kopi O.jpg' WHERE id = '1413';
UPDATE hpbdata SET image = '/images/Milo drink less sweet.jpg' WHERE id = '1626';
UPDATE hpbdata SET image = '/images/Dim sum you tiao.jpg' WHERE id = '935';
UPDATE hpbdata SET image = '/images/Dim sum siew mai steamed.jpg' WHERE id = '933';
UPDATE hpbdata SET image = '/images/Steamed mantou.jpg' WHERE id = '2549';
UPDATE hpbdata SET image = '/images/Pan-fried turnip cake.jpg' WHERE id = '1888';
UPDATE hpbdata SET image = '/images/Steamed sui kow.jpg' WHERE id = '2555';
UPDATE hpbdata SET image = '/images/Soon kway steamed.jpg' WHERE id = '2447';
UPDATE hpbdata SET image = '/images/Char siew chee cheong fun.jpg' WHERE id = '518';
UPDATE hpbdata SET image = '/images/Chicken rice with roasted chicken.jpg' WHERE id = '619';
UPDATE hpbdata SET image = '/images/Yong tau foo mixed items noodles not included.jpg' WHERE id = '2953';
UPDATE hpbdata SET image = '/images/Hot and spicy beef noodles soup.jpg' WHERE id = '1302';
UPDATE hpbdata SET image = '/images/Deep fried fish bee hoon soup with milk.jpg' WHERE id = '912';
UPDATE hpbdata SET image = '/images/Nasi Lemak with chicken wing.jpg' WHERE id = '1719';
UPDATE hpbdata SET image = '/images/Mutton briyani.jpg' WHERE id = '1696';
UPDATE hpbdata SET image = '/images/Popiah.jpg' WHERE id = '2046';
UPDATE hpbdata SET image = '/images/Nonya rice dumpling.jpg' WHERE id = '1738';
UPDATE hpbdata SET image = '/images/Chapati.jpg' WHERE id = '515';
UPDATE hpbdata SET image = '/images/Chinese rojak.jpg' WHERE id = '713';
UPDATE hpbdata SET image = '/images/Hokkien mee.jpg' WHERE id = '1289';
UPDATE hpbdata SET image = '/images/Fried rice with lap cheong and salted fish.jpg' WHERE id = '1147';
UPDATE hpbdata SET image = '/images/Bak kut teh soup only.jpg' WHERE id = '104';
UPDATE hpbdata SET image = '/images/Hong Kong wanton noodles dry.jpg' WHERE id = '1298';
UPDATE hpbdata SET image = '/images/Vegetarian fried bee hoon.jpg' WHERE id = '2862';
UPDATE hpbdata SET image = '/images/Jemput pisang.jpg' WHERE id = '1369';
UPDATE hpbdata SET image = '/images/Kaya cake.jpg' WHERE id = '1394';
UPDATE hpbdata SET image = '/images/Muah chee.jpg' WHERE id = '1659';
UPDATE hpbdata SET image = '/images/Durian pudding.jpg' WHERE id = '981';
UPDATE hpbdata SET image = '/images/Banana fritter.jpg' WHERE id = '124';
UPDATE hpbdata SET image = '/images/Cracker peanut.jpg' WHERE id = '831';
UPDATE hpbdata SET image = '/images/Coconut kueh tutu.jpg' WHERE id = '771';
UPDATE hpbdata SET image = '/images/Kesari.jpg' WHERE id = '1399';
UPDATE hpbdata SET image = '/images/Curry puff chicken.jpg' WHERE id = '878';
UPDATE hpbdata SET image = '/images/Bak kua pork with lean and fat.jpg' WHERE id = '101';
UPDATE hpbdata SET image = '/images/Pandan chiffon cake.jpg' WHERE id = '1886';
UPDATE hpbdata SET image = '/images/Mee siam.jpg' WHERE id = '1589';
UPDATE hpbdata SET image = '/images/Laksa.jpg' WHERE id = '1442';
UPDATE hpbdata SET image = '/images/Lor mee.jpg' WHERE id = '1517';
UPDATE hpbdata SET image = '/images/Lontong goreng.jpg' WHERE id = '1511';
UPDATE hpbdata SET image = '/images/Chilli crab.jpg' WHERE id = '701';
UPDATE hpbdata SET image = '/images/Seafood porridge.jpg' WHERE id = '2385';
UPDATE hpbdata SET image = '/images/Ban mian soup.jpg' WHERE id = '114';
UPDATE hpbdata SET image = '/images/Kway teow goreng.jpg' WHERE id = '1438';
UPDATE hpbdata SET image = '/images/Claypot rice with mixed vegetable.jpg' WHERE id = '758';
UPDATE hpbdata SET image = '/images/Char kway teow.jpg' WHERE id = '516';
UPDATE hpbdata SET image = '/images/Chicken porridge.jpg' WHERE id = '615';
UPDATE hpbdata SET image = '/images/Fish ball noodles soup.jpg' WHERE id = '1040';
UPDATE hpbdata SET image = '/images/Tom yam noodle soup.jpg' WHERE id = '2745';
UPDATE hpbdata SET image = '/images/Kway chap.jpg' WHERE id = '1436';
UPDATE hpbdata SET image = '/images/Duck with salted vegetable soup.jpg' WHERE id = '966';
UPDATE hpbdata SET image = '/images/Nasi goreng.jpg' WHERE id = '1715';
